package me.activated.core.database.redis.payload.action;

public enum JedisAction {

    SERVER_DATA, PLAYER_DATA, PLAYER_MESSAGE, RANKS_UPDATE, PERMISSIONS_UPDATE, REPORT_SAVE, STAFF_CONNECT, STAFF_SWITCH, STAFF_DISCONNECT,
    EXECUTE_PUNISHMENT, EXECUTE_UNBLACKLIST, EXECUTE_UNMUTE, EXECUTE_UNBAN, EXECUTE_ALT_KICK,
    TAGS_UPDATE, SERVER_COMMAND, LEFT_FROZEN, JOIN_ME, GRANTS_UPDATE, PLAYER_PERMISSIONS_UPDATE,
    SERVER_ONLINE, SERVER_OFFLINE
}
